// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANIcIw3VA3QYWDsq8f-FJ7nBc89EPpgkc',
    appId: '1:258070342745:web:c7b1731393a36a3bf65548',
    messagingSenderId: '258070342745',
    projectId: 'john-441b1',
    authDomain: 'john-441b1.firebaseapp.com',
    storageBucket: 'john-441b1.firebasestorage.app',
    measurementId: 'G-NLY2T73G9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjYcFGoOhPTykE6NA7mUKvi1-Rov3ksJI',
    appId: '1:258070342745:android:aa566c818fb9ad99f65548',
    messagingSenderId: '258070342745',
    projectId: 'john-441b1',
    storageBucket: 'john-441b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5HQeV7DziIqTt0tDMe_HANL2d0KvfZ6E',
    appId: '1:258070342745:ios:d0827fbb48945fd5f65548',
    messagingSenderId: '258070342745',
    projectId: 'john-441b1',
    storageBucket: 'john-441b1.firebasestorage.app',
    iosBundleId: 'com.store.mrjohn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5HQeV7DziIqTt0tDMe_HANL2d0KvfZ6E',
    appId: '1:258070342745:ios:5c4b0d296fb17739f65548',
    messagingSenderId: '258070342745',
    projectId: 'john-441b1',
    storageBucket: 'john-441b1.firebasestorage.app',
    iosBundleId: 'com.example.storeManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANIcIw3VA3QYWDsq8f-FJ7nBc89EPpgkc',
    appId: '1:258070342745:web:bf31682ce56b6d74f65548',
    messagingSenderId: '258070342745',
    projectId: 'john-441b1',
    authDomain: 'john-441b1.firebaseapp.com',
    storageBucket: 'john-441b1.firebasestorage.app',
    measurementId: 'G-VXQ6NGK5MK',
  );

}